### ISSUE TITLE
エマさんだけ情報が取得できない

### ISSUE THREAD

**Issue by okohs** [gdg-tokyo/rapid#7]
Webサイトのこれが動いて、
`/devfest2019/session/shoko-sato`
これが動かない
`/devfest2019/session/haruka-emma-iwao`

API側の問題なきがするのでこっちに切ります。

**Comment by kappa0923** [comment]
これFirestoreが `emma-haruka-iwao` だからです。
どっちが正しいですか？

**Comment by okohs** [comment]
`Haruka Ema  Iwao` ってフォームには入力してるからこっちが正しいかも！
（TwitterはEmma Haruka Iwaoだからややこし）
